spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth
          uri: http://auth-service:8084
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: hotel
          uri: http://hotel-service:8081
          predicates:
            - Path=/api/hotels/**, /api/rooms/**
          filters:
            - StripPrefix=0
        - id: reservation
          uri: http://reservation-service:8082
          predicates:
            - Path=/api/reservations/**
          filters:
            - StripPrefix=0
services:
    auth:
      base-url: http://localhost:8084
      connect-timeout-ms: 5000
      read-timeout-ms: 5000
server:
  port: 8080
